"""initial schema

Revision ID: a97bc88abcff
Revises: 
Create Date: 2026-05-01 15:44:55.749370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a97bc88abcff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('body_hash', sa.Text(), nullable=False),
    sa.Column('raw_body', sa.LargeBinary(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_status', sa.Text(), server_default=sa.text("'received'"), nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'provider', 'idempotency_key')
    )
    op.create_table('event_processing_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # --- Postgres-specific: trigger for updated_at on tenants ---
    op.execute("""
        CREATE OR REPLACE FUNCTION update_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER set_updated_at
        BEFORE UPDATE ON tenants
        FOR EACH ROW
        EXECUTE FUNCTION update_updated_at();
    """)

    # --- CHECK constraints ---
    op.execute("""
        ALTER TABLE events ADD CONSTRAINT events_current_status_check
        CHECK (current_status IN ('received', 'processing', 'processed', 'failed'));
    """)
    op.execute("""
        ALTER TABLE event_processing_attempts ADD CONSTRAINT attempts_status_check
        CHECK (status IN ('started', 'succeeded', 'failed'));
    """)

    # --- Composite index on events ---
    op.execute("""
        CREATE INDEX events_tenant_status_received_idx
        ON events (tenant_id, current_status, received_at);
    """)

    # --- RLS on events ---
    op.execute("ALTER TABLE events ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE events FORCE ROW LEVEL SECURITY;")
    op.execute("""
        CREATE POLICY tenant_isolation ON events
        USING (tenant_id = current_setting('app.current_tenant')::UUID)
        WITH CHECK (tenant_id = current_setting('app.current_tenant')::UUID);
    """)

    # --- RLS on event_processing_attempts ---
    op.execute("ALTER TABLE event_processing_attempts ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE event_processing_attempts FORCE ROW LEVEL SECURITY;")
    op.execute("""
        CREATE POLICY tenant_isolation ON event_processing_attempts
        USING (tenant_id = current_setting('app.current_tenant')::UUID)
        WITH CHECK (tenant_id = current_setting('app.current_tenant')::UUID);
    """)

    # --- Grants for app user ---
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON tenants, events, event_processing_attempts TO tenantflow_app;")

def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON event_processing_attempts;")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON events;")
    op.execute("DROP TRIGGER IF EXISTS set_updated_at ON tenants;")
    op.execute("DROP FUNCTION IF EXISTS update_updated_at();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_processing_attempts')
    op.drop_table('events')
    op.drop_table('tenants')
    # ### end Alembic commands ###
